import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Karel',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'AVASTA Brasiilia',
      slug: 'avasta-brasiilia',
      category: 'Kohvioad',
      image: '/images/AVASTA Brasiilia.png',
      isFeatured: true,
      featuredImage: '/images/banner1.png',
      price: 14.9,
      brand: 'AVASTA',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description:
        '“Avasta” Brasiilia on 100% araabikast valmistatud mahe tassitäis, mille maitsenüanssidest tõusevad esile šokolaad, järelmaitsest aga kodune sarapuupähkel, ploom ja kakao. Madal happesus ja täidlane maitse loovad mõnusa koosluse, mida nautida iga ilmaga. Brasiilia maitserännakule võid minna nii musta kui ka piimakohviga – täpselt nii, nagu Sulle meeldib. Samuti ei pea Sa muretsema, et Sinu seade ei võimalda Brasiiliasse rännata, sest “Avasta” sobib avastamiseks iga kohvimasinaga. Kohviubade kasvupiirkond on Santose regioonis, 900-1100m merepinnast.',
    },
    {
      name: 'AVASTA Brasiilia kofeiinivaba',
      slug: 'avasta-brasiilia-kofeiinivaba',
      category: 'Kohvioad',
      image: '/images/AVASTA Brasiilia kofeiinivaba.png',
      isFeatured: true,
      featuredImage: '/images/banner2.png',
      price: 16.9,
      brand: 'AVASTA',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'AVASTA Brasiilia kofeiinivaba - kirjeldus',
    },
    {
      name: 'AVASTA Etioopia',
      slug: 'avasta-etioopia',
      category: 'Kohvioad',
      image: '/images/AVASTA Etioopia.png',
      price: 14.9,
      brand: 'AVASTA',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'AVASTA Etioopia - kirjeldus',
    },
    {
      name: 'AVASTA Kolumbia',
      slug: 'avasta-kolumbia',
      category: 'Kohvioad',
      image: '/images/AVASTA Kolumbia.png',
      price: 14.9,
      brand: 'AVASTA',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'AVASTA Kolumbia - kirjeldus',
    },
    {
      name: 'AVASTA Mehhiko',
      slug: 'avasta-mehhiko',
      category: 'Kohvioad',
      image: '/images/AVASTA Mehhiko.png',
      price: 14.9,
      brand: 'AVASTA',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'AVASTA Mehhiko - kirjeldus',
    },
    {
      name: 'AVASTA Guatemala',
      slug: 'avasta-guatemala',
      category: 'Kohvioad',
      image: '/images/AVASTA Guatemala.png',
      price: 17.9,
      brand: 'AVASTA',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'AVASTA Guatemala - kirjeldus',
    },
    {
      name: 'AVASTA Costa Rica',
      slug: 'avasta-costa-rica',
      category: 'Kohvioad',
      image: '/images/AVASTA Costa Rica.png',
      price: 17.9,
      brand: 'AVASTA',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'AVASTA Costa Rica - kirjeldus',
    },
    {
      name: 'AVASTA Paapua Uus-Guinea',
      slug: 'avasta-paapua-uus-guinea',
      category: 'Kohvioad',
      image: '/images/AVASTA Paapua Uus-Guinea.png',
      price: 17.9,
      brand: 'AVASTA',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'AVASTA Paapua Uus-Guinea - kirjeldus',
    },
    {
      name: 'AVASTA Tansaania',
      slug: 'avasta-tansaania',
      category: 'Kohvioad',
      image: '/images/AVASTA Tansaania.png',
      price: 17.9,
      brand: 'AVASTA',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'AVASTA Tansaania - kirjeldus',
    },
    {
      name: 'Best Beans Classic',
      slug: 'best-beans-classic',
      category: 'Kohvioad',
      image: '/images/Best Beans Classic.png',
      price: 13.9,
      brand: 'BestBeans',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Best Beans Classic - kirjeldus',
    },
    {
      name: 'Best Beans Espresso Superiore',
      slug: 'best-beans-espresso-superiore',
      category: 'Kohvioad',
      image: '/images/Best Beans Espresso Superiore.png',
      price: 14.9,
      brand: 'BestBeans',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Best Beans Espresso Superiore - kirjeldus',
    },
    {
      name: 'Best Beans Supreme',
      slug: 'best-beans-supreme',
      category: 'Kohvioad',
      image: '/images/Best Beans Supreme.png',
      price: 16.9,
      brand: 'BestBeans',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Best Beans Supreme - kirjeldus',
    },
    {
      name: 'Tasuja Emmi',
      slug: 'tasuja-emmi',
      category: 'Kohvioad',
      image: '/images/Tasuja Emmi.png',
      price: 13.9,
      brand: 'Tasuja',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'Tasuja Emmi - kirjeldus',
    },
    {
      name: 'Tasuja Tambet',
      slug: 'tasuja-tambet',
      category: 'Kohvioad',
      image: '/images/Tasuja Tambet.png',
      price: 13.9,
      brand: 'Tasuja',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'Tasuja Tambet - kirjeldus',
    },
    {
      name: 'Tasuja Wahur',
      slug: 'tasuja-wahur',
      category: 'Kohvioad',
      image: '/images/Tasuja Wahur.png',
      price: 13.9,
      brand: 'Tasuja',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'Tasuja Wahur - kirjeldus',
    },
    {
      name: 'Tasuja Jaanus',
      slug: 'tasuja-jaanus',
      category: 'Kohvioad',
      image: '/images/Tasuja Jaanus.png',
      price: 13.9,
      brand: 'Tasuja',
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: 'Tasuja Jaanus - kirjeldus',
    },
  ],
};
export default data;
